# Generated by Django 3.0.7 on 2020-06-20 19:37

from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models


class Migration(migrations.Migration):

    replaces = [('word', '0001_initial'), ('word', '0002_auto_20200620_2008'), ('word', '0003_auto_20200621_0432'), ('word', '0004_auto_20200621_0434')]

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('user', '0003_auto_20200621_0432'),
        ('glossary', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', django_mysql.models.JSONField(default=dict, verbose_name='名前')),
                ('deleted', models.DateTimeField(null=True, verbose_name='削除日')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='更新日')),
                ('created_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_user_id', to='user.User')),
                ('deleted_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deleted_user_id', to='user.User')),
                ('glossary_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='glossary.Glossary')),
                ('modified_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modified_user_id', to='user.User')),
            ],
        ),
        migrations.AlterModelTable(
            name='word',
            table='word',
        ),
        migrations.AlterField(
            model_name='word',
            name='deleted',
            field=models.DateTimeField(blank=True, null=True, verbose_name='削除日'),
        ),
        migrations.AlterField(
            model_name='word',
            name='deleted_user_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='deleted_user_id', to='user.User'),
        ),
        migrations.AlterField(
            model_name='word',
            name='info',
            field=django_mysql.models.JSONField(default=dict, verbose_name='属性'),
        ),
        migrations.AddField(
            model_name='word',
            name='word',
            field=models.CharField(max_length=255, verbose_name='単語'),
        ),
    ]
