# Generated by Django 3.0.7 on 2020-06-20 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20200621_0432'),
        ('word', '0001_squashed_0004_auto_20200621_0434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='deleted_user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deleted_user_id', to='user.User'),
        ),
    ]
