# Generated by Django 3.0.7 on 2020-06-20 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('glossary', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='名前')),
                ('email', models.EmailField(max_length=255, verbose_name='メールアドレス')),
                ('memo', models.TextField(null=True, verbose_name='メモ')),
                ('deleted', models.DateTimeField(null=True, verbose_name='削除日')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='更新日')),
            ],
        ),
        migrations.CreateModel(
            name='GlossaryUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_id', models.IntegerField(choices=[(1, 'Admin'), (2, 'Nomal'), (3, 'ReadOnly')], verbose_name='Role')),
                ('deleted', models.DateTimeField(null=True, verbose_name='削除日')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='更新日')),
                ('glossary_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='glossary.Glossary')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User')),
            ],
        ),
    ]
